parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - standard
rules:
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/indent': 'off'
  no-unused-vars: 'off'